theme = "catppuccin_mocha"

[editor]
mouse = false
cursorline = true
insert-final-newline = true
auto-format = true

[editor.auto-save]
focus-lost = true

[editor.auto-save.after-delay]
enable = true
timeout = 5000

[editor.statusline]
left = ["spinner", "read-only-indicator", "file-name", "primary-selection-length"]
center = []
right = ["position-percentage"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "all"
nbsp = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false # Show any files starting with "."

[keys.normal]
"C-o" = "file_picker"
"C-k" = "buffer_picker"
"tab" = "rotate_view"
"S-tab" = "rotate_view_reverse"
# Also Ctrl+s to add an item to the jumplist manually
"C-h" = "jump_backward"
"C-l" = "jump_forward"
